name: learn-github-actions
on: 
  pull_request:
    branches:
      - main
concurrency:
  group: test_x
  cancel-in-progress: false
jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - name: step one
      - run: echo "i am step 1"
  test2:
    needs: [test1]
    runs-on: ubuntu-latest
    steps:
      - name: step two
      - run: echo "i am only running after test1"
      - run: echo "i am step 2"
    
